# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='samplesheet',
            field=models.FileField(blank=True, default=b'', upload_to=b''),
        ),
    ]
